import Foundation

/// Generates plain-text crash analysis reports
public struct TextReporter: Sendable {

    /// Generate a text report from a parsed dump and optional analysis
    public static func generateReport(
        from dump: ParsedMinidump,
        analysis: CrashAnalysis?,
        fileName: String = "Minidump",
        verbose: Bool = false
    ) -> String {
        var lines: [String] = []

        // Header
        lines.append("=" .repeated(72))
        lines.append("  Crash Dump Analysis Report")
        lines.append("  Generated by MiniDumpTruck")
        lines.append("=" .repeated(72))
        lines.append("")

        // File info
        lines.append("File: \(fileName)")
        lines.append("Timestamp: \(dump.header.timestamp.formatted())")
        lines.append("Size: \(ByteCountFormatter.string(fromByteCount: Int64(dump.data.count), countStyle: .file))")
        lines.append("Flags: \(dump.header.flagsDescription.joined(separator: ", "))")
        lines.append("")

        // Parse warnings
        if !dump.parseWarnings.isEmpty {
            lines.append("-" .repeated(72))
            lines.append("PARSE WARNINGS (\(dump.parseWarnings.count))")
            lines.append("-" .repeated(72))
            for warning in dump.parseWarnings {
                let stream = warning.streamType?.displayName ?? "Unknown"
                lines.append("  [!] \(stream): \(warning.message.sanitizedForOutput())")
            }
            lines.append("")
        }

        // System Info
        if let sysInfo = dump.systemInfo {
            lines.append("-" .repeated(72))
            lines.append("SYSTEM INFORMATION")
            lines.append("-" .repeated(72))
            // Sanitize dump-sourced strings before emitting to a
            // terminal — strips ANSI escapes / bidi marks / null bytes
            // that a crafted dump could embed in module names, version
            // strings, etc.
            lines.append("  OS: \(sysInfo.windowsVersionName) (\(sysInfo.osVersionString.sanitizedForOutput()))")
            lines.append("  Architecture: \(sysInfo.processorArchitecture.displayName)")
            lines.append("  Processors: \(sysInfo.numberOfProcessors)")
            lines.append("  Product Type: \(sysInfo.productType.displayName)")
            if let csd = sysInfo.csdVersion, !csd.isEmpty {
                lines.append("  Service Pack: \(csd.sanitizedForOutput())")
            }
            if sysInfo.cpuInfo.isX86 {
                lines.append("  CPU Vendor: \(sysInfo.cpuInfo.vendorString.sanitizedForOutput())")
                lines.append("  CPU Family/Model: Family \(sysInfo.cpuInfo.displayFamily), Model \(sysInfo.cpuInfo.displayModel), Stepping \(sysInfo.cpuInfo.stepping)")
            }
            lines.append("")
        }

        // Process Info
        if let miscInfo = dump.miscInfo {
            if miscInfo.processId != nil || miscInfo.processCreateTime != nil {
                lines.append("-" .repeated(72))
                lines.append("PROCESS INFORMATION")
                lines.append("-" .repeated(72))
                if let pid = miscInfo.processId {
                    lines.append("  Process ID: \(pid)")
                }
                if let createTime = miscInfo.formattedCreateTime {
                    lines.append("  Created: \(createTime)")
                }
                if let uptime = miscInfo.processUptime {
                    lines.append("  CPU Time: \(uptime)")
                }
                if let freq = miscInfo.processorFrequency {
                    lines.append("  Processor Frequency: \(freq)")
                }
                if let integrity = miscInfo.integrityLevelDescription {
                    lines.append("  Integrity Level: \(integrity.sanitizedForOutput())")
                }
                if let tz = miscInfo.timeZoneName {
                    lines.append("  Timezone: \(tz.sanitizedForOutput())")
                }
                if let build = miscInfo.buildString {
                    lines.append("  Build String: \(build.sanitizedForOutput())")
                }
                lines.append("")
            }
        }

        // Exception
        if let exception = dump.exception {
            lines.append("-" .repeated(72))
            lines.append("EXCEPTION")
            lines.append("-" .repeated(72))
            lines.append("  Code: \(String(format: "0x%08X", exception.exceptionCode)) (\(exception.exceptionName))")
            lines.append("  Description: \(exception.exceptionDescription)")
            lines.append("  Address: \(String(format: "0x%016llX", exception.exceptionAddress))")
            if let module = dump.moduleList?.module(containing: exception.exceptionAddress) {
                lines.append("  Module: \(module.shortName.sanitizedForOutput())")
            }
            lines.append("  Thread ID: \(exception.threadId)")
            if let details = exception.accessViolationDetails {
                lines.append("  Details: \(details)")
            }
            lines.append("")
        }

        // Analysis
        if let analysis = analysis {
            lines.append("-" .repeated(72))
            lines.append("CRASH ANALYSIS (Confidence: \(analysis.confidence.displayName))")
            lines.append("-" .repeated(72))

            let summary = analysis.crashSummary
            lines.append("  Exception: \(summary.exceptionType)")
            lines.append("  Faulting Address: \(String(format: "0x%016llX", summary.faultingAddress))")
            if let module = summary.faultingModule {
                lines.append("  Faulting Module: \(module.shortName.sanitizedForOutput())")
            }
            // probableCause/recommendation are composed by CrashAnalyzer
            // and embed module.shortName, which is dump-sourced. Sanitize
            // here as well as at the direct shortName interpolation sites
            // so ANSI escapes in module names can't sneak in via the
            // analyzer's generated text.
            lines.append("  Probable Cause: \(summary.probableCause.sanitizedForOutput())")
            lines.append("  Recommendation: \(summary.recommendation.sanitizedForOutput())")
            lines.append("")

            if let blame = analysis.blameModule {
                lines.append("  BLAMED MODULE: \(blame.module.shortName.sanitizedForOutput())")
                if let version = blame.module.version {
                    lines.append("  Version: \(version.fileVersion.sanitizedForOutput())")
                }
                lines.append("  Reason: \(blame.reasonDescription)")
                lines.append("")
            }

            // Stack trace
            if !analysis.stackFrames.isEmpty {
                lines.append("  Call Stack:")
                for (i, frame) in analysis.stackFrames.enumerated() {
                    let typeStr: String
                    switch frame.frameType {
                    case .instructionPointer: typeStr = "IP"
                    case .returnAddress: typeStr = "Ret"
                    case .framePointer: typeStr = "FP"
                    }
                    let confStr: String
                    switch frame.confidence {
                    case .high: confStr = "H"
                    case .medium: confStr = "M"
                    case .low: confStr = "L"
                    }
                    let addr = String(format: "0x%016llX", frame.address)
                    lines.append("    #\(String(format: "%2d", i)) [\(typeStr)] \(addr) \(frame.displayAddress.sanitizedForOutput()) [\(confStr)]")
                }
                lines.append("")
            }
        }

        // Threads
        if let threadList = dump.threadList, !threadList.threads.isEmpty {
            lines.append("-" .repeated(72))
            lines.append("THREADS (\(threadList.threads.count))")
            lines.append("-" .repeated(72))

            for thread in threadList.threads {
                let name = dump.threadNames?.name(for: thread.id)
                let isFaulting = thread.id == dump.exception?.threadId
                var threadLine = "  Thread \(thread.id)"
                if let name = name { threadLine += " (\(name.sanitizedForOutput()))" }
                if isFaulting { threadLine += " *FAULTING*" }
                threadLine += " - \(thread.priorityDescription)"
                lines.append(threadLine)

                if verbose, let ctx = thread.context {
                    // Architecture-neutral first line (IP / SP / FP). Then
                    // an architecture-specific second line so x64 callers
                    // still see RAX-RDX and ARM64 callers see X0-X3.
                    lines.append("    \(ctx.ipRegisterName)=\(String(format: "0x%016llX", ctx.instructionPointer)) \(ctx.spRegisterName)=\(String(format: "0x%016llX", ctx.stackPointer)) \(ctx.fpRegisterName)=\(String(format: "0x%016llX", ctx.framePointer))")
                    switch ctx {
                    case .amd64(let amd):
                        lines.append("    RAX=\(String(format: "0x%016llX", amd.rax)) RBX=\(String(format: "0x%016llX", amd.rbx)) RCX=\(String(format: "0x%016llX", amd.rcx)) RDX=\(String(format: "0x%016llX", amd.rdx))")
                    case .arm64(let arm):
                        lines.append("    X0=\(String(format: "0x%016llX", arm.xRegs[0])) X1=\(String(format: "0x%016llX", arm.xRegs[1])) X2=\(String(format: "0x%016llX", arm.xRegs[2])) X3=\(String(format: "0x%016llX", arm.xRegs[3]))")
                    }
                }
            }
            lines.append("")
        }

        // Modules
        if let moduleList = dump.moduleList, !moduleList.modules.isEmpty {
            lines.append("-" .repeated(72))
            lines.append("MODULES (\(moduleList.modules.count))")
            lines.append("-" .repeated(72))

            for module in moduleList.modules {
                let addr = String(format: "0x%016llX", module.baseAddress)
                let size = ByteCountFormatter.string(fromByteCount: Int64(module.sizeOfImage), countStyle: .file)
                let version = module.version?.fileVersion ?? ""
                lines.append("  \(addr) \(module.shortName.sanitizedForOutput()) (\(size)) \(version.sanitizedForOutput())")
            }
            lines.append("")
        }

        // Verbose: Memory regions
        if verbose, let memoryInfoList = dump.memoryInfoList, !memoryInfoList.entries.isEmpty {
            lines.append("-" .repeated(72))
            lines.append("MEMORY REGIONS (\(memoryInfoList.entries.count))")
            lines.append("-" .repeated(72))

            for entry in memoryInfoList.entries {
                let addr = String(format: "0x%016llX", entry.baseAddress)
                let size = ByteCountFormatter.string(fromByteCount: Int64(clamping: entry.regionSize), countStyle: .file)
                lines.append("  \(addr) \(size) \(entry.state.displayName) \(entry.protect.shortDescription) \(entry.type.displayName)")
            }
            lines.append("")
        }

        // Footer
        lines.append("=" .repeated(72))
        lines.append("  Report generated by MiniDumpTruck")
        lines.append("=" .repeated(72))

        return lines.joined(separator: "\n")
    }
}

private extension String {
    func repeated(_ count: Int) -> String {
        String(repeating: self, count: count)
    }
}
