import Foundation
import Testing

@Suite("CLI Integration Tests")
struct CLITests {
    // MARK: - Test Infrastructure

    struct CLIResult {
        let stdout: String
        let stderr: String
        let exitCode: Int32
    }

    static var cliBinary: URL {
        var url = URL(fileURLWithPath: #file)
        while url.path != "/" {
            url = url.deletingLastPathComponent()
            if FileManager.default.fileExists(atPath: url.appendingPathComponent("Package.swift").path) {
                return url.appendingPathComponent(".build/debug/minidumptruck-cli")
            }
        }
        fatalError("Could not find project root")
    }

    static var testDataPath: String {
        var url = URL(fileURLWithPath: #file)
        while url.path != "/" {
            url = url.deletingLastPathComponent()
            if FileManager.default.fileExists(atPath: url.appendingPathComponent("Package.swift").path) {
                return url.appendingPathComponent("TestData").path
            }
        }
        return ""
    }

    static func testFile(_ name: String) -> URL {
        URL(fileURLWithPath: testDataPath).appendingPathComponent(name)
    }

    static func runCLI(_ args: String...) throws -> CLIResult {
        try runCLI(args)
    }

    static func runCLI(_ args: [String]) throws -> CLIResult {
        let process = Process()
        process.executableURL = cliBinary
        process.arguments = args

        let stdoutPipe = Pipe()
        let stderrPipe = Pipe()
        process.standardOutput = stdoutPipe
        process.standardError = stderrPipe

        try process.run()
        process.waitUntilExit()

        let stdoutData = stdoutPipe.fileHandleForReading.readDataToEndOfFile()
        let stderrData = stderrPipe.fileHandleForReading.readDataToEndOfFile()

        return CLIResult(
            stdout: String(data: stdoutData, encoding: .utf8) ?? "",
            stderr: String(data: stderrData, encoding: .utf8) ?? "",
            exitCode: process.terminationStatus
        )
    }

    // MARK: - 1. Help & Version

    @Test func helpPrintsUsageAndExitsZero() throws {
        let result = try Self.runCLI("--help")
        #expect(result.exitCode == 0)
        #expect(result.stdout.contains("USAGE"))
        #expect(result.stdout.contains("analyze"))
        #expect(result.stdout.contains("export"))
        #expect(result.stdout.contains("info"))
    }

    @Test func versionPrintsVersionAndExitsZero() throws {
        let result = try Self.runCLI("--version")
        #expect(result.exitCode == 0)
        #expect(result.stdout.contains("1.0.0"))
    }

    @Test func analyzeHelpPrintsAnalyzeOptions() throws {
        let result = try Self.runCLI("analyze", "--help")
        #expect(result.exitCode == 0)
        #expect(result.stdout.contains("USAGE"))
        #expect(result.stdout.contains("--verbose"))
        #expect(result.stdout.contains("--summary"))
    }

    @Test func infoHelpPrintsInfoOptions() throws {
        let result = try Self.runCLI("info", "--help")
        #expect(result.exitCode == 0)
        #expect(result.stdout.contains("USAGE"))
        #expect(result.stdout.contains("<path>"))
    }

    @Test func manualPrintsManualAndExitsZero() throws {
        let result = try Self.runCLI("--manual")
        #expect(result.exitCode == 0)
        #expect(result.stdout.contains("MiniDumpTruck CLI Manual"))
    }

    @Test func manualContainsKeySections() throws {
        let result = try Self.runCLI("--manual")
        #expect(result.stdout.contains("Commands"))
        #expect(result.stdout.contains("analyze"))
        #expect(result.stdout.contains("export"))
        #expect(result.stdout.contains("info"))
    }

    // MARK: - 2. AnalyzeCommand

    @Test func analyzeSingleFilePrintsReport() throws {
        let url = Self.testFile("test.dmp")
        try #require(FileManager.default.fileExists(atPath: url.path))

        let result = try Self.runCLI("analyze", url.path)

        #expect(result.stdout.contains("Crash Dump Analysis Report"))
        #expect(result.stdout.contains("SYSTEM INFORMATION"))
        #expect(result.stdout.contains("MODULES"))
        #expect(result.stdout.contains("THREADS"))
        #expect(result.stdout.contains("Report generated by MiniDumpTruck"))
    }

    @Test func analyzeSingleFileWithCrashExitsWithCode2() throws {
        let url = Self.testFile("test.dmp")
        try #require(FileManager.default.fileExists(atPath: url.path))

        let result = try Self.runCLI("analyze", url.path)

        // test.dmp has an exception, so exit code should be 2
        #expect(result.exitCode == 2)
    }

    @Test func analyzeVerboseIncludesRegisters() throws {
        let url = Self.testFile("test.dmp")
        try #require(FileManager.default.fileExists(atPath: url.path))

        let result = try Self.runCLI("analyze", "--verbose", url.path)

        #expect(result.stdout.contains("RIP="))
        #expect(result.stdout.contains("RSP="))
    }

    @Test func analyzeNonVerboseExcludesRegisters() throws {
        let url = Self.testFile("test.dmp")
        try #require(FileManager.default.fileExists(atPath: url.path))

        let result = try Self.runCLI("analyze", url.path)

        #expect(!result.stdout.contains("RIP="))
        #expect(!result.stdout.contains("RSP="))
    }

    @Test func analyzeDirectoryBatchPrintsSummary() throws {
        let path = Self.testDataPath
        try #require(FileManager.default.fileExists(atPath: path))

        let result = try Self.runCLI("analyze", path)

        #expect(result.stdout.contains("Total files:"))
        #expect(result.stdout.contains("Successfully parsed:"))
    }

    @Test func analyzeDirectorySummaryOnlyOmitsIndividualReports() throws {
        let path = Self.testDataPath
        try #require(FileManager.default.fileExists(atPath: path))

        let result = try Self.runCLI("analyze", "--summary", path)

        #expect(result.stdout.contains("Total files:"))
        // Summary-only should not include individual report headers
        #expect(!result.stdout.contains("Crash Dump Analysis Report"))
    }

    @Test func analyzeMissingFileExitsNonZero() throws {
        let result = try Self.runCLI("analyze", "/nonexistent/path/missing.dmp")

        #expect(result.exitCode != 0)
        #expect(result.stderr.contains("File or directory not found"))
    }

    @Test func analyzeDirectoryWithCorruptFileEmitsStderrLine() throws {
        let good = Self.testFile("test.dmp")
        try #require(FileManager.default.fileExists(atPath: good.path))

        let tmpDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("cli-test-mixed-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: tmpDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tmpDir) }

        try FileManager.default.copyItem(at: good, to: tmpDir.appendingPathComponent("good.dmp"))
        let badName = "corrupt.dmp"
        try Data(repeating: 0x41, count: 64).write(to: tmpDir.appendingPathComponent(badName))

        let result = try Self.runCLI("analyze", "--summary", tmpDir.path)

        #expect(result.stdout.contains("Total files:"))
        #expect(result.stdout.contains("Failed to parse: 1"))
        #expect(result.stderr.contains(badName))
        // Reason should be present after "<file>: " — non-empty content.
        let stderrLine = result.stderr.split(separator: "\n").first { $0.hasPrefix(badName + ":") }
        let line = try #require(stderrLine)
        let reason = line.dropFirst(badName.count + 1).trimmingCharacters(in: .whitespaces)
        #expect(!reason.isEmpty)
    }

    @Test func analyzeDirectoryWithNoDmpFiles() throws {
        let tmpDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("cli-test-empty-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: tmpDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tmpDir) }

        let result = try Self.runCLI("analyze", tmpDir.path)

        #expect(result.stdout.contains("No .dmp files found") || result.stderr.contains("No .dmp files found"))
    }

    // MARK: - 3. ExportCommand

    @Test func exportAsTextCreatesFile() throws {
        let url = Self.testFile("test.dmp")
        try #require(FileManager.default.fileExists(atPath: url.path))

        let tmpDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("cli-test-export-\(UUID().uuidString)")
        defer { try? FileManager.default.removeItem(at: tmpDir) }

        let result = try Self.runCLI("export", "-f", "text", "-o", tmpDir.path, url.path)

        #expect(result.exitCode == 0)
        let files = try FileManager.default.contentsOfDirectory(atPath: tmpDir.path)
        #expect(files.contains(where: { $0.hasSuffix(".txt") }))
    }

    @Test func exportAsJsonCreatesValidJson() throws {
        let url = Self.testFile("test.dmp")
        try #require(FileManager.default.fileExists(atPath: url.path))

        let tmpDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("cli-test-json-\(UUID().uuidString)")
        defer { try? FileManager.default.removeItem(at: tmpDir) }

        let result = try Self.runCLI("export", "-f", "json", "-o", tmpDir.path, url.path)

        #expect(result.exitCode == 0)
        let files = try FileManager.default.contentsOfDirectory(atPath: tmpDir.path)
        let jsonFile = try #require(files.first(where: { $0.hasSuffix(".json") }))

        let data = try Data(contentsOf: tmpDir.appendingPathComponent(jsonFile))
        let json = try JSONSerialization.jsonObject(with: data)
        #expect(json is [String: Any])
    }

    @Test func exportAsHtmlCreatesFile() throws {
        let url = Self.testFile("test.dmp")
        try #require(FileManager.default.fileExists(atPath: url.path))

        let tmpDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("cli-test-html-\(UUID().uuidString)")
        defer { try? FileManager.default.removeItem(at: tmpDir) }

        let result = try Self.runCLI("export", "-f", "html", "-o", tmpDir.path, url.path)

        #expect(result.exitCode == 0)
        let files = try FileManager.default.contentsOfDirectory(atPath: tmpDir.path)
        let htmlFile = try #require(files.first(where: { $0.hasSuffix(".html") }))

        let content = try String(contentsOf: tmpDir.appendingPathComponent(htmlFile), encoding: .utf8)
        #expect(content.contains("<!DOCTYPE html>"))
    }

    @Test func exportAsCsvCreatesFile() throws {
        let url = Self.testFile("test.dmp")
        try #require(FileManager.default.fileExists(atPath: url.path))

        let tmpDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("cli-test-csv-\(UUID().uuidString)")
        defer { try? FileManager.default.removeItem(at: tmpDir) }

        let result = try Self.runCLI("export", "-f", "csv", "-o", tmpDir.path, url.path)

        #expect(result.exitCode == 0)
        let files = try FileManager.default.contentsOfDirectory(atPath: tmpDir.path)
        #expect(files.contains(where: { $0.hasSuffix(".csv") }))

        let csvFile = try #require(files.first(where: { $0.hasSuffix(".csv") }))
        let data = try Data(contentsOf: tmpDir.appendingPathComponent(csvFile))
        // CSV files from CSVExporter start with UTF-8 BOM
        #expect(data.starts(with: [0xEF, 0xBB, 0xBF]))
    }

    @Test func exportDirectoryBatchCreatesMultipleFiles() throws {
        let path = Self.testDataPath
        try #require(FileManager.default.fileExists(atPath: path))

        // Count .dmp files in test data directory
        let dmpFiles = try FileManager.default.contentsOfDirectory(atPath: path)
            .filter { $0.hasSuffix(".dmp") }
        try #require(!dmpFiles.isEmpty)

        let tmpDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("cli-test-batch-\(UUID().uuidString)")
        defer { try? FileManager.default.removeItem(at: tmpDir) }

        let result = try Self.runCLI("export", "-f", "text", "-o", tmpDir.path, path)

        #expect(result.exitCode == 0)
        let outputFiles = try FileManager.default.contentsOfDirectory(atPath: tmpDir.path)
            .filter { $0.hasSuffix(".txt") }
        #expect(outputFiles.count == dmpFiles.count)
    }

    @Test func exportMissingFileExitsNonZero() throws {
        let result = try Self.runCLI("export", "/nonexistent/path/missing.dmp")

        #expect(result.exitCode != 0)
        #expect(result.stderr.contains("File or directory not found"))
    }

    // MARK: - 4. InfoCommand

    @Test func infoSingleFilePrintsDetails() throws {
        let url = Self.testFile("test.dmp")
        try #require(FileManager.default.fileExists(atPath: url.path))

        let result = try Self.runCLI("info", url.path)

        #expect(result.exitCode == 0)
        #expect(result.stdout.contains("File:"))
        #expect(result.stdout.contains("Streams:"))
        #expect(result.stdout.contains("System Info:") || result.stdout.contains("OS:"))
    }

    @Test func infoMissingFileExitsNonZero() throws {
        let result = try Self.runCLI("info", "/nonexistent/path/missing.dmp")

        #expect(result.exitCode != 0)
        #expect(result.stderr.contains("File or directory not found"))
    }

    @Test func infoShowsExceptionDetails() throws {
        let url = Self.testFile("test.dmp")
        try #require(FileManager.default.fileExists(atPath: url.path))

        let result = try Self.runCLI("info", url.path)

        #expect(result.exitCode == 0)
        // test.dmp has an exception
        #expect(result.stdout.contains("Exception:"))
        #expect(result.stdout.contains("Code:"))
        #expect(result.stdout.contains("Address:"))
    }

    @Test func infoOutputContainsExpectedLabels() throws {
        let url = Self.testFile("test.dmp")
        try #require(FileManager.default.fileExists(atPath: url.path))

        let result = try Self.runCLI("info", url.path)

        #expect(result.exitCode == 0)
        #expect(result.stdout.contains("File:"))
        #expect(result.stdout.contains("Streams:"))
        #expect(result.stdout.contains("Timestamp:"))
    }

    // MARK: - 5. Error Handling

    @Test func noArgumentsPrintsHelp() throws {
        let result = try Self.runCLI()

        // ArgumentParser with a default subcommand that requires an argument
        // will print usage/error when no arguments given
        #expect(result.exitCode != 0)
    }

    @Test func invalidSubcommandPrintsError() throws {
        let result = try Self.runCLI("boguscommand")

        #expect(result.exitCode != 0)
    }

    @Test func exportWithInvalidFormatPrintsError() throws {
        let url = Self.testFile("test.dmp")
        let result = try Self.runCLI("export", "-f", "yaml", url.path)

        #expect(result.exitCode != 0)
    }
}
