import Foundation
import Testing
@testable import MiniDumpTruckCore

@Suite("TextReporter Tests")
struct TextReporterTests {

    // MARK: - Test Data Paths

    static var testDataPath: String {
        var url = URL(fileURLWithPath: #file)
        while url.path != "/" {
            url = url.deletingLastPathComponent()
            if FileManager.default.fileExists(atPath: url.appendingPathComponent("Package.swift").path) {
                return url.appendingPathComponent("TestData").path
            }
        }
        return ""
    }

    static func testFile(_ name: String) -> URL {
        URL(fileURLWithPath: testDataPath).appendingPathComponent(name)
    }

    // MARK: - Structure Tests

    @Test func reportContainsHeader() throws {
        let url = Self.testFile("test.dmp")
        try #require(FileManager.default.fileExists(atPath: url.path))

        let data = try Data(contentsOf: url)
        let dump = try MinidumpParser.parse(data: data)
        let report = TextReporter.generateReport(from: dump, analysis: nil)

        #expect(report.contains("Crash Dump Analysis Report"))
        #expect(report.contains("Generated by MiniDumpTruck"))
    }

    @Test func reportContainsFileName() throws {
        let url = Self.testFile("test.dmp")
        try #require(FileManager.default.fileExists(atPath: url.path))

        let data = try Data(contentsOf: url)
        let dump = try MinidumpParser.parse(data: data)
        let report = TextReporter.generateReport(from: dump, analysis: nil, fileName: "mycrash.dmp")

        #expect(report.contains("File: mycrash.dmp"))
    }

    @Test func reportContainsSystemInfo() throws {
        let url = Self.testFile("test.dmp")
        try #require(FileManager.default.fileExists(atPath: url.path))

        let data = try Data(contentsOf: url)
        let dump = try MinidumpParser.parse(data: data)

        guard dump.systemInfo != nil else { return }

        let report = TextReporter.generateReport(from: dump, analysis: nil)
        #expect(report.contains("SYSTEM INFORMATION"))
        #expect(report.contains("Architecture:"))
        #expect(report.contains("Processors:"))
    }

    @Test func reportContainsException() throws {
        let url = Self.testFile("test.dmp")
        try #require(FileManager.default.fileExists(atPath: url.path))

        let data = try Data(contentsOf: url)
        let dump = try MinidumpParser.parse(data: data)

        guard dump.exception != nil else { return }

        let report = TextReporter.generateReport(from: dump, analysis: nil)
        #expect(report.contains("EXCEPTION"))
        #expect(report.contains("Code:"))
        #expect(report.contains("Address:"))
        #expect(report.contains("Thread ID:"))
    }

    @Test func reportContainsThreads() throws {
        let url = Self.testFile("test.dmp")
        try #require(FileManager.default.fileExists(atPath: url.path))

        let data = try Data(contentsOf: url)
        let dump = try MinidumpParser.parse(data: data)

        guard let threadList = dump.threadList, !threadList.threads.isEmpty else { return }

        let report = TextReporter.generateReport(from: dump, analysis: nil)
        #expect(report.contains("THREADS"))
    }

    @Test func reportContainsModules() throws {
        let url = Self.testFile("test.dmp")
        try #require(FileManager.default.fileExists(atPath: url.path))

        let data = try Data(contentsOf: url)
        let dump = try MinidumpParser.parse(data: data)

        guard let moduleList = dump.moduleList, !moduleList.modules.isEmpty else { return }

        let report = TextReporter.generateReport(from: dump, analysis: nil)
        #expect(report.contains("MODULES"))
    }

    @Test func reportContainsAnalysis() throws {
        let url = Self.testFile("test.dmp")
        try #require(FileManager.default.fileExists(atPath: url.path))

        let data = try Data(contentsOf: url)
        let dump = try MinidumpParser.parse(data: data)
        let analysis = CrashAnalyzer(dump: dump).analyze()

        let report = TextReporter.generateReport(from: dump, analysis: analysis)

        if analysis != nil {
            #expect(report.contains("CRASH ANALYSIS"))
            #expect(report.contains("Call Stack:"))
            #expect(report.contains("Probable Cause:"))
            #expect(report.contains("Recommendation:"))
        }
    }

    @Test func reportContainsBlamedModule() throws {
        let url = Self.testFile("full-dump.dmp")
        try #require(FileManager.default.fileExists(atPath: url.path))

        let data = try Data(contentsOf: url)
        let dump = try MinidumpParser.parse(data: data)
        let analysis = CrashAnalyzer(dump: dump).analyze()

        let report = TextReporter.generateReport(from: dump, analysis: analysis)

        if analysis?.blameModule != nil {
            #expect(report.contains("BLAMED MODULE:"))
            #expect(report.contains("Reason:"))
        }
    }

    @Test func reportContainsConfidence() throws {
        let url = Self.testFile("full-dump.dmp")
        try #require(FileManager.default.fileExists(atPath: url.path))

        let data = try Data(contentsOf: url)
        let dump = try MinidumpParser.parse(data: data)
        let analysis = CrashAnalyzer(dump: dump).analyze()

        let report = TextReporter.generateReport(from: dump, analysis: analysis)

        if analysis != nil {
            #expect(report.contains("Confidence:"))
        }
    }

    @Test func reportContainsFooter() throws {
        let url = Self.testFile("test.dmp")
        try #require(FileManager.default.fileExists(atPath: url.path))

        let data = try Data(contentsOf: url)
        let dump = try MinidumpParser.parse(data: data)
        let report = TextReporter.generateReport(from: dump, analysis: nil)

        #expect(report.contains("Report generated by MiniDumpTruck"))
    }

    @Test func verboseIncludesRegisters() throws {
        let url = Self.testFile("test.dmp")
        try #require(FileManager.default.fileExists(atPath: url.path))

        let data = try Data(contentsOf: url)
        let dump = try MinidumpParser.parse(data: data)

        guard let threadList = dump.threadList,
              threadList.threads.contains(where: { $0.context != nil }) else { return }

        let report = TextReporter.generateReport(from: dump, analysis: nil, verbose: true)
        #expect(report.contains("RIP="))
        #expect(report.contains("RSP="))
    }

    @Test func nonVerboseExcludesRegisters() throws {
        let url = Self.testFile("test.dmp")
        try #require(FileManager.default.fileExists(atPath: url.path))

        let data = try Data(contentsOf: url)
        let dump = try MinidumpParser.parse(data: data)
        let report = TextReporter.generateReport(from: dump, analysis: nil, verbose: false)

        #expect(!report.contains("RIP="))
    }

    @Test func verboseIncludesMemoryRegions() throws {
        let url = Self.testFile("test.dmp")
        try #require(FileManager.default.fileExists(atPath: url.path))

        let data = try Data(contentsOf: url)
        let dump = try MinidumpParser.parse(data: data)

        guard dump.memoryInfoList != nil else { return }

        let verboseReport = TextReporter.generateReport(from: dump, analysis: nil, verbose: true)
        let normalReport = TextReporter.generateReport(from: dump, analysis: nil, verbose: false)

        #expect(verboseReport.contains("MEMORY REGIONS"))
        #expect(!normalReport.contains("MEMORY REGIONS"))
    }

    @Test func reportMarksFaultingThread() throws {
        let url = Self.testFile("test.dmp")
        try #require(FileManager.default.fileExists(atPath: url.path))

        let data = try Data(contentsOf: url)
        let dump = try MinidumpParser.parse(data: data)

        guard dump.exception != nil,
              let threadList = dump.threadList, !threadList.threads.isEmpty else { return }

        let report = TextReporter.generateReport(from: dump, analysis: nil)
        #expect(report.contains("*FAULTING*"))
    }

    @Test func reportWithMinimalDump() {
        let dump = createMinimalDump()
        let report = TextReporter.generateReport(from: dump, analysis: nil)

        #expect(report.contains("Crash Dump Analysis Report"))
        #expect(report.contains("Report generated by MiniDumpTruck"))
    }

    @Test func reportStripsAnsiAndBidiFromAnalysisStrings() throws {
        // CrashAnalyzer composes probableCause/recommendation by
        // interpolating module.shortName, which is dump-sourced and
        // attacker-influenced. Verify TextReporter strips ANSI escapes
        // and bidi overrides even when they arrive via these composed
        // fields rather than direct shortName interpolation.
        let dump = createMinimalDump()
        let summary = CrashSummary(
            exceptionType: "ACCESS_VIOLATION",
            exceptionDescription: "test",
            faultingAddress: 0x1000,
            faultingModule: nil,
            probableCause: "module evil\u{001B}[2J.dll dereferenced null at \u{202E}backwards",
            recommendation: "investigate ntdll\u{0000}\u{200E}.dll for memory corruption"
        )
        let analysis = CrashAnalysis(
            stackFrames: [],
            blameModule: nil,
            crashSummary: summary,
            confidence: .medium
        )

        let report = TextReporter.generateReport(from: dump, analysis: analysis)

        #expect(!report.contains("\u{001B}"))
        #expect(!report.contains("\u{202E}"))
        #expect(!report.contains("\u{0000}"))
        #expect(!report.contains("\u{200E}"))
        // Non-control content still appears.
        #expect(report.contains("evil"))
        #expect(report.contains("[2J"))  // bracket text after ESC strip
        #expect(report.contains("investigate ntdll"))
    }

    // MARK: - Helpers

    private func createMinimalDump() -> ParsedMinidump {
        var data = Data(repeating: 0, count: 32)
        data[0] = 0x4D; data[1] = 0x44; data[2] = 0x4D; data[3] = 0x50
        data[4] = 0x93; data[5] = 0xA7
        data[12] = 32
        let header = MinidumpHeader(from: data)!
        let streamDir = StreamDirectory(from: data, header: header)!
        return ParsedMinidump(header: header, streamDirectory: streamDir, data: data)
    }
}
